// frontend/src/features/products/components/product-info.tsx
import { Star } from "lucide-react";

interface ProductInfoProps {
  title: string;
  price: string;
  rating?: number;
  reviews?: number;
  description?: string;
  specifications?: Array<{ title: string; value: string }>;
}

export function ProductInfo({
  title,
  price,
  rating,
  reviews,
  description,
  specifications,
}: ProductInfoProps) {
  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">{title}</h1>

      {rating && (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1">
            <Star className="w-5 h-5 fill-current text-yellow-500" />
            <span className="font-semibold">{rating}</span>
          </div>
          {reviews && (
            <span className="text-sm text-muted-foreground">
              ({reviews.toLocaleString()} reviews)
            </span>
          )}
        </div>
      )}

      <div className="text-3xl font-bold text-primary">{price}</div>

      {description && (
        <div className="space-y-2">
          <h3 className="font-semibold">Description</h3>
          <p className="text-muted-foreground">{description}</p>
        </div>
      )}

      {specifications && specifications.length > 0 && (
        <div className="space-y-2">
          <h3 className="font-semibold">Specifications</h3>
          <div className="grid grid-cols-2 gap-2 text-sm">
            {specifications.map((spec, index) => (
              <div key={index} className="flex flex-col">
                <span className="text-muted-foreground">{spec.title}</span>
                <span className="font-medium">{spec.value}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// angular-front/src/app/features/products/components/product-info/product-info.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

export interface ProductSpecification {
  title: string;
  value: string;
}

@Component({
  selector: 'app-product-info',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  templateUrl: './product-info.component.html',
  styleUrl: './product-info.component.scss',
})
export class ProductInfoComponent {
  title = input.required<string>();
  price = input.required<string>();
  rating = input<number>();
  reviews = input<number>();
  description = input<string>();
  specifications = input<ProductSpecification[]>();

  formatNumber(num: number): string {
    return num.toLocaleString();
  }
}

<div class="space-y-4">
  <!-- Title -->
  <h1 class="text-2xl font-bold">{{ title() }}</h1>

  <!-- Rating & Reviews -->
  @if (rating()) {
    <div class="flex items-center gap-2">
      <div class="flex items-center gap-1">
        <mat-icon class="!w-5 !h-5 !text-[20px] text-yellow-500">star</mat-icon>
        <span class="font-semibold">{{ rating() }}</span>
      </div>
      @if (reviews()) {
        <span class="text-sm text-muted-foreground">
          ({{ formatNumber(reviews()!) }} reviews)
        </span>
      }
    </div>
  }

  <!-- Price -->
  <div class="text-3xl font-bold text-primary">{{ price() }}</div>

  <!-- Description -->
  @if (description()) {
    <div class="space-y-2">
      <h3 class="font-semibold">Description</h3>
      <p class="text-muted-foreground">{{ description() }}</p>
    </div>
  }

  <!-- Specifications -->
  @if (specifications() && specifications()!.length > 0) {
    <div class="space-y-2">
      <h3 class="font-semibold">Specifications</h3>
      <div class="grid grid-cols-2 gap-2 text-sm">
        @for (spec of specifications(); track $index) {
          <div class="flex flex-col">
            <span class="text-muted-foreground">{{ spec.title }}</span>
            <span class="font-medium">{{ spec.value }}</span>
          </div>
        }
      </div>
    </div>
  }
</div>
