// angular-front/src/app/features/products/components/product-image-gallery/product-image-gallery.component.ts
import { Component, input, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-product-image-gallery',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule],
  templateUrl: './product-image-gallery.component.html',
  styleUrl: './product-image-gallery.component.scss',
})
export class ProductImageGalleryComponent {
  images = input.required<string[]>();
  title = input.required<string>();

  currentIndex = signal(0);

  nextImage(): void {
    const current = this.currentIndex();
    if (current < this.images().length - 1) {
      this.currentIndex.set(current + 1);
    }
  }

  prevImage(): void {
    const current = this.currentIndex();
    if (current > 0) {
      this.currentIndex.set(current - 1);
    }
  }

  selectImage(index: number): void {
    this.currentIndex.set(index);
  }

  getCurrentImage(): string {
    const images = this.images();
    return images[this.currentIndex()] || '/placeholder.png';
  }
}

@if (images().length === 0) {
  <div class="aspect-square bg-muted rounded-xl flex items-center justify-center">
    <span class="text-muted-foreground">No image available</span>
  </div>
} @else {
  <div class="space-y-4">
    <!-- Main Image -->
    <div class="relative aspect-square bg-muted rounded-xl overflow-hidden">
      <img
        [src]="getCurrentImage()"
        [alt]="title()"
        class="w-full h-full object-cover"
      />

      @if (images().length > 1) {
        <!-- Previous Button -->
        <button
          mat-icon-button
          (click)="prevImage()"
          [disabled]="currentIndex() === 0"
          class="absolute left-2 top-1/2 -translate-y-1/2 !w-10 !h-10 !rounded-full bg-background/80 backdrop-blur-sm hover:bg-background disabled:opacity-50 transition-all"
          aria-label="Previous image"
        >
          <mat-icon>chevron_left</mat-icon>
        </button>

        <!-- Next Button -->
        <button
          mat-icon-button
          (click)="nextImage()"
          [disabled]="currentIndex() === images().length - 1"
          class="absolute right-2 top-1/2 -translate-y-1/2 !w-10 !h-10 !rounded-full bg-background/80 backdrop-blur-sm hover:bg-background disabled:opacity-50 transition-all"
          aria-label="Next image"
        >
          <mat-icon>chevron_right</mat-icon>
        </button>
      }
    </div>

    <!-- Thumbnail Navigation -->
    @if (images().length > 1) {
      <div class="flex gap-2 overflow-x-auto pb-2">
        @for (img of images(); track $index) {
          <button
            (click)="selectImage($index)"
            [class]="'flex-shrink-0 w-20 h-20 rounded-lg overflow-hidden border-2 transition-colors ' + (currentIndex() === $index ? 'border-primary' : 'border-border')"
            [attr.aria-label]="'View image ' + ($index + 1)"
          >
            <img
              [src]="img"
              [alt]="title() + ' ' + ($index + 1)"
              class="w-full h-full object-cover"
            />
          </button>
        }
      </div>
    }
  </div>
}

// frontend/src/features/products/components/product-image-gallery.tsx
"use client";

import { useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";

interface ProductImageGalleryProps {
  images: string[];
  title: string;
}

export function ProductImageGallery({
  images,
  title,
}: ProductImageGalleryProps) {
  const [currentIndex, setCurrentIndex] = useState(0);

  const nextImage = () => {
    if (currentIndex < images.length - 1) {
      setCurrentIndex(currentIndex + 1);
    }
  };

  const prevImage = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1);
    }
  };

  if (!images || images.length === 0) {
    return (
      <div className="aspect-square bg-muted rounded-xl flex items-center justify-center">
        <span className="text-muted-foreground">No image available</span>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="relative aspect-square bg-muted rounded-xl overflow-hidden">
        <img
          src={images[currentIndex] || "/placeholder.png"}
          alt={title}
          className="w-full h-full object-cover"
        />
        {images.length > 1 && (
          <>
            <button
              onClick={prevImage}
              disabled={currentIndex === 0}
              className="absolute left-2 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-background/80 backdrop-blur-sm hover:bg-background disabled:opacity-50 flex items-center justify-center transition-all"
              aria-label="Previous image"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <button
              onClick={nextImage}
              disabled={currentIndex === images.length - 1}
              className="absolute right-2 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-background/80 backdrop-blur-sm hover:bg-background disabled:opacity-50 flex items-center justify-center transition-all"
              aria-label="Next image"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </>
        )}
      </div>

      {images.length > 1 && (
        <div className="flex gap-2 overflow-x-auto pb-2">
          {images.map((img, index) => (
            <button
              key={index}
              onClick={() => setCurrentIndex(index)}
              className={`flex-shrink-0 w-20 h-20 rounded-lg overflow-hidden border-2 transition-colors ${
                currentIndex === index ? "border-primary" : "border-border"
              }`}
              aria-label={`View image ${index + 1}`}
            >
              <img
                src={img}
                alt={`${title} ${index + 1}`}
                className="w-full h-full object-cover"
              />
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
