// angular-front/src/app/features/products/components/product-rating-breakdown/product-rating-breakdown.component.ts
import { Component, input, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

export interface RatingItem {
  stars: number;
  amount: number;
}

@Component({
  selector: 'app-product-rating-breakdown',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  templateUrl: './product-rating-breakdown.component.html',
  styleUrl: './product-rating-breakdown.component.scss',
})
export class ProductRatingBreakdownComponent {
  ratings = input.required<RatingItem[]>();

  maxAmount = computed(() => {
    const ratingList = this.ratings();
    if (!ratingList || ratingList.length === 0) return 0;
    return Math.max(...ratingList.map((r) => r.amount));
  });

  getPercentageWidth(amount: number): string {
    const max = this.maxAmount();
    if (max === 0) return '0%';
    return `${(amount / max) * 100}%`;
  }

  formatNumber(num: number): string {
    return num.toLocaleString();
  }
}

@if (ratings() && ratings().length > 0) {
  <div class="space-y-4">
    <h2 class="text-xl font-bold">Rating Breakdown</h2>

    <div class="space-y-2">
      @for (rating of ratings(); track $index) {
        <div class="flex items-center gap-3">
          <span class="w-12 text-sm font-medium">
            {{ rating.stars }}
            <mat-icon class="!w-3 !h-3 !text-[12px] inline">star</mat-icon>
          </span>
          <div class="flex-1 h-2 bg-muted rounded-full overflow-hidden">
            <div
              class="h-full bg-primary transition-all"
              [style.width]="getPercentageWidth(rating.amount)"
            ></div>
          </div>
          <span class="w-16 text-sm text-muted-foreground text-right">
            {{ formatNumber(rating.amount) }}
          </span>
        </div>
      }
    </div>
  </div>
}

// frontend/src/features/products/components/product-rating-breakdown.tsx
import { Star } from "lucide-react";

interface RatingItem {
  stars: number;
  amount: number;
}

interface ProductRatingBreakdownProps {
  ratings: RatingItem[];
}

export function ProductRatingBreakdown({ ratings }: ProductRatingBreakdownProps) {
  if (!ratings || ratings.length === 0) return null;

  const maxAmount = Math.max(...ratings.map((r) => r.amount));

  return (
    <div className="space-y-4">
      <h2 className="text-xl font-bold">Rating Breakdown</h2>
      <div className="space-y-2">
        {ratings.map((rating, index) => (
          <div key={index} className="flex items-center gap-3">
            <span className="w-12 text-sm font-medium">
              {rating.stars} <Star className="w-3 h-3 inline" />
            </span>
            <div className="flex-1 h-2 bg-muted rounded-full overflow-hidden">
              <div
                className="h-full bg-primary transition-all"
                style={{
                  width: `${(rating.amount / maxAmount) * 100}%`,
                }}
              />
            </div>
            <span className="w-16 text-sm text-muted-foreground text-right">
              {rating.amount.toLocaleString()}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
