// frontend/src/features/products/components/ProductDrawer.tsx
"use client";

import { useEffect, useState } from "react";
import { getProductDetails } from "@/lib/api";
import { ProductDetailsResponse } from "@/types";
import { useChatStore } from "@/lib/store";
import { Drawer } from "./ui/drawer";
import { ProductImageGallery } from "./product/product-image-gallery";
import { ProductInfo } from "./product/product-info";
import { ProductOffers } from "./product/product-offers";
import { ProductRatingBreakdown } from "./product/product-rating-breakdown";
import { ProductSimilarItems } from "./product/product-similar-items";
import { ProductDrawerSkeleton } from "./ui/product-skeletons";

interface ProductDrawerProps {
  pageToken: string;
  onClose: () => void;
}

export function ProductDrawer({ pageToken, onClose }: ProductDrawerProps) {
  const [product, setProduct] = useState<ProductDetailsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const { country } = useChatStore();

  useEffect(() => {
    const fetchDetails = async () => {
      try {
        const details = await getProductDetails(pageToken, country);
        setProduct(details);
      } catch (error) {
        console.error("Failed to load product details:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchDetails();
  }, [pageToken, country]);

  return (
    <Drawer isOpen={true} onClose={onClose}>
      {loading ? (
        <ProductDrawerSkeleton />
      ) : product ? (
        <div className="space-y-8 animate-fade-in">
          <ProductImageGallery
            images={product.images || []}
            title={product.title}
          />

          <ProductInfo
            title={product.title}
            price={product.price}
            rating={product.rating}
            reviews={product.reviews}
            description={product.description}
            specifications={product.specifications}
          />

          <ProductOffers offers={product.offers || []} />

          <ProductRatingBreakdown ratings={product.rating_breakdown || []} />

          <ProductSimilarItems products={product.more_options || []} />
        </div>
      ) : (
        <div className="flex items-center justify-center h-96 animate-fade-in">
          <div className="text-center space-y-2">
            <p className="text-muted-foreground text-lg">Failed to load product details</p>
            <button
              onClick={onClose}
              className="text-primary hover:underline text-sm"
            >
              Close and try again
            </button>
          </div>
        </div>
      )}
    </Drawer>
  );
}

// angular-front/src/app/features/products/components/product-drawer/product-drawer.component.ts
import {
  Component,
  input,
  output,
  signal,
  inject,
  OnInit,
  effect,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { ApiService } from '../../../../core/services/api.service';
import { AuthStore } from '../../../../core/stores/auth.store';
import { ProductDetailsResponse } from '../../../../shared/types';
import { ProductImageGalleryComponent } from '../product-image-gallery/product-image-gallery.component';
import { ProductInfoComponent } from '../product-info/product-info.component';
import { ProductOffersComponent } from '../product-offers/product-offers.component';
import { ProductRatingBreakdownComponent } from '../product-rating-breakdown/product-rating-breakdown.component';
import { ProductSimilarItemsComponent } from '../product-similar-items/product-similar-items.component';
import { ProductDrawerSkeletonComponent } from '../product-drawer-skeleton/product-drawer-skeleton.component';

@Component({
  selector: 'app-product-drawer',
  standalone: true,
  imports: [
    CommonModule,
    MatSidenavModule,
    MatButtonModule,
    MatIconModule,
    ProductImageGalleryComponent,
    ProductInfoComponent,
    ProductOffersComponent,
    ProductRatingBreakdownComponent,
    ProductSimilarItemsComponent,
    ProductDrawerSkeletonComponent,
  ],
  templateUrl: './product-drawer.component.html',
  styleUrl: './product-drawer.component.scss',
})
export class ProductDrawerComponent implements OnInit {
  pageToken = input.required<string>();
  isOpen = input.required<boolean>();
  closed = output<void>();

  private apiService = inject(ApiService);
  private authStore = inject(AuthStore);

  product = signal<ProductDetailsResponse | null>(null);
  loading = signal(true);
  error = signal(false);

  constructor() {
    // Watch for pageToken changes and refetch
    effect(() => {
      const token = this.pageToken();
      if (token && this.isOpen()) {
        this.fetchProductDetails();
      }
    });
  }

  ngOnInit(): void {
    if (this.pageToken() && this.isOpen()) {
      this.fetchProductDetails();
    }
  }

  private fetchProductDetails(): void {
    this.loading.set(true);
    this.error.set(false);

    const accessToken = this.authStore.accessToken();

    this.apiService.getProductDetails(this.pageToken(), accessToken ?? undefined).subscribe({
      next: (details) => {
        this.product.set(details);
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Failed to load product details:', err);
        this.error.set(true);
        this.loading.set(false);
      },
    });
  }

  handleClose(): void {
    this.closed.emit();
  }

  retry(): void {
    this.fetchProductDetails();
  }
}

<mat-drawer-container class="product-drawer-container" [hasBackdrop]="true">
  <mat-drawer
    #drawer
    mode="over"
    position="end"
    [opened]="isOpen()"
    (closed)="handleClose()"
    class="product-drawer"
  >
    <!-- Header -->
    <div
      class="sticky top-0 z-10 bg-background/95 backdrop-blur-sm border-b border-border p-4 flex items-center justify-between"
    >
      <button
        mat-icon-button
        (click)="handleClose()"
        class="!w-10 !h-10 !rounded-full bg-secondary hover:bg-secondary/80 transition-colors ml-auto"
        aria-label="Close drawer"
      >
        <mat-icon>close</mat-icon>
      </button>
    </div>

    <!-- Content -->
    <div class="p-6">
      @if (loading()) {
        <app-product-drawer-skeleton />
      } @else if (error()) {
        <div
          class="flex items-center justify-center h-96 animate-fade-in"
        >
          <div class="text-center space-y-2">
            <p class="text-muted-foreground text-lg">
              Failed to load product details
            </p>
            <button
              (click)="retry()"
              class="text-primary hover:underline text-sm"
            >
              Retry
            </button>
            <button
              (click)="handleClose()"
              class="text-primary hover:underline text-sm block"
            >
              Close and try again
            </button>
          </div>
        </div>
      } @else if (product()) {
        <div class="space-y-8 animate-fade-in">
          <app-product-image-gallery
            [images]="product()!.images || []"
            [title]="product()!.title"
          />

          <app-product-info
            [title]="product()!.title"
            [price]="product()!.price"
            [rating]="product()!.rating"
            [reviews]="product()!.reviews"
            [description]="product()!.description"
            [specifications]="product()!.specifications"
          />

          <app-product-offers [offers]="product()!.offers || []" />

          <app-product-rating-breakdown
            [ratings]="product()!.rating_breakdown || []"
          />

          <app-product-similar-items
            [products]="product()!.more_options || []"
          />
        </div>
      }
    </div>
  </mat-drawer>
</mat-drawer-container>
