// angular-front/src/app/features/products/components/product-offers/product-offers.component.ts
import { Component, input, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { ProductOffer } from '../../../../shared/types';

@Component({
  selector: 'app-product-offers',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule],
  templateUrl: './product-offers.component.html',
  styleUrl: './product-offers.component.scss',
})
export class ProductOffersComponent {
  offers = input.required<ProductOffer[]>();

  bestPriceOffer = computed(() => {
    const offerList = this.offers();
    if (!offerList || offerList.length === 0) return null;

    return offerList.reduce((best, current) => {
      const bestPrice = best.extracted_total || best.extracted_price || Infinity;
      const currentPrice =
        current.extracted_total || current.extracted_price || Infinity;
      return currentPrice < bestPrice ? current : best;
    }, offerList[0]);
  });

  isBestPrice(offer: ProductOffer): boolean {
    const best = this.bestPriceOffer();
    return best === offer && this.offers().length > 1;
  }

  hasMonthlyPayment(offer: ProductOffer): boolean {
    return !!(
      offer.monthly_payment_duration && offer.monthly_payment_duration > 0
    );
  }

  formatNumber(num: number): string {
    return num.toLocaleString();
  }

  onImageError(event: Event): void {
    const target = event.target as HTMLImageElement;
    target.style.display = 'none';
  }
}

@if (offers() && offers().length > 0) {
  <div class="space-y-4">
    <h2 class="text-xl font-bold">
      Available from {{ offers().length }}
      {{ offers().length === 1 ? 'store' : 'stores' }}
    </h2>

    <div class="space-y-3">
      @for (offer of offers(); track $index) {
        <div
          [class]="
            'relative flex flex-col gap-4 p-4 rounded-xl border transition-all ' +
            (isBestPrice(offer)
              ? 'bg-primary/5 border-primary/40 shadow-md'
              : 'bg-secondary border-border hover:border-primary/30')
          "
        >
          <!-- Best Price Tag -->
          @if (isBestPrice(offer) || offer.tag) {
            <div
              class="absolute -top-2 -right-2 px-3 py-1 rounded-full bg-primary text-primary-foreground text-xs font-bold shadow-lg flex items-center gap-1"
            >
              <mat-icon class="!w-3 !h-3 !text-[12px]">local_offer</mat-icon>
              {{ offer.tag || 'Best price' }}
            </div>
          }

          <div class="flex flex-col sm:flex-row gap-4">
            <!-- Store Logo & Info -->
            <div class="flex-1 space-y-3">
              <div class="flex items-center gap-3">
                @if (offer.logo) {
                  <div class="relative w-8 h-8 flex-shrink-0">
                    <img
                      [src]="offer.logo"
                      [alt]="offer.merchant"
                      class="w-full h-full object-contain"
                      (error)="onImageError($event)"
                    />
                  </div>
                }
                <div class="flex-1 min-w-0">
                  <div class="font-semibold text-lg truncate">
                    {{ offer.merchant }}
                  </div>
                  @if (offer.title) {
                    <div class="text-sm text-muted-foreground line-clamp-1">
                      {{ offer.title }}
                    </div>
                  }
                </div>
              </div>

              <!-- Pricing -->
              <div class="space-y-1">
                @if (hasMonthlyPayment(offer)) {
                  <div>
                    <div class="text-3xl font-bold text-primary">
                      {{ offer.price }}
                      <span class="text-sm font-normal text-muted-foreground ml-2">
                        /mo for {{ offer.monthly_payment_duration }} months
                      </span>
                    </div>
                    @if (offer.down_payment && offer.down_payment !== '$0.00') {
                      <div class="text-sm text-muted-foreground">
                        Down payment: {{ offer.down_payment }}
                      </div>
                    }
                    @if (offer.total) {
                      <div class="text-sm text-muted-foreground">
                        Total: {{ offer.total }}
                      </div>
                    }
                  </div>
                } @else {
                  <div class="text-3xl font-bold text-primary">
                    {{ offer.price }}
                  </div>
                }

                <div class="flex flex-wrap gap-2 text-sm">
                  @if (offer.shipping) {
                    <div
                      [class]="
                        offer.shipping.toLowerCase().includes('free')
                          ? 'text-green-600 dark:text-green-500 font-medium'
                          : 'text-muted-foreground'
                      "
                    >
                      <mat-icon class="!w-3.5 !h-3.5 !text-[14px] inline mr-1"
                        >local_shipping</mat-icon
                      >
                      {{ offer.shipping }}
                    </div>
                  }
                  @if (offer.total && !hasMonthlyPayment(offer)) {
                    <div class="text-muted-foreground">
                      Total: {{ offer.total }}
                    </div>
                  }
                </div>
              </div>

              <!-- Rating & Reviews -->
              @if (offer.rating || offer.reviews) {
                <div class="flex items-center gap-3 text-sm">
                  @if (offer.rating) {
                    <div
                      class="flex items-center gap-1 text-yellow-600 dark:text-yellow-500"
                    >
                      <mat-icon class="!w-4 !h-4 !text-[16px]">star</mat-icon>
                      <span class="font-medium">{{ offer.rating }}</span>
                    </div>
                  }
                  @if (offer.reviews) {
                    <div class="text-muted-foreground">
                      ({{ formatNumber(offer.reviews) }}
                      {{ offer.reviews === 1 ? 'review' : 'reviews' }})
                    </div>
                  }
                </div>
              }

              <!-- Payment Methods -->
              @if (offer.payment_methods) {
                <div class="text-sm text-muted-foreground flex items-center gap-1">
                  <mat-icon class="!w-3.5 !h-3.5 !text-[14px]"
                    >credit_card</mat-icon
                  >
                  {{ offer.payment_methods }}
                </div>
              }

              <!-- Details and Offers -->
              @if (offer.details_and_offers && offer.details_and_offers.length > 0) {
                <div class="space-y-1">
                  @for (detail of offer.details_and_offers; track $index) {
                    <div class="text-sm text-muted-foreground flex items-start gap-2">
                      <mat-icon
                        class="!w-4 !h-4 !text-[16px] text-green-600 dark:text-green-500 flex-shrink-0 mt-0.5"
                        >check</mat-icon
                      >
                      <span>{{ detail }}</span>
                    </div>
                  }
                </div>
              }

              <!-- Availability -->
              @if (offer.availability) {
                <div class="text-sm text-green-600 dark:text-green-500 font-medium">
                  {{ offer.availability }}
                </div>
              }
            </div>

            <!-- View Offer Button -->
            <a
              [href]="offer.link"
              target="_blank"
              rel="noopener noreferrer"
              class="px-6 py-3 bg-primary text-primary-foreground rounded-full font-semibold hover:opacity-90 transition-opacity flex items-center justify-center gap-2 whitespace-nowrap self-start sm:self-center h-fit"
            >
              View Offer
              <mat-icon class="!w-4 !h-4 !text-[16px]">open_in_new</mat-icon>
            </a>
          </div>
        </div>
      }
    </div>
  </div>
}

// frontend/src/components/product/product-offers.tsx
import { ExternalLink, Star, Check, CreditCard, Package, Tag as TagIcon } from "lucide-react";
import Image from "next/image";

interface Offer {
  merchant: string;
  logo?: string;
  price: string;
  extracted_price?: number;
  currency?: string;
  link: string;
  title?: string;
  availability?: string;
  shipping?: string;
  shipping_extracted?: number;
  total?: string;
  extracted_total?: number;
  rating?: number | string;
  reviews?: number;
  payment_methods?: string;
  tag?: string;
  details_and_offers?: string[];
  monthly_payment_duration?: number;
  down_payment?: string;
}

interface ProductOffersProps {
  offers: Offer[];
}

export function ProductOffers({ offers }: ProductOffersProps) {
  if (!offers || offers.length === 0) return null;

  // Find best price offer
  const bestPriceOffer = offers.reduce((best, current) => {
    const bestPrice = best.extracted_total || best.extracted_price || Infinity;
    const currentPrice = current.extracted_total || current.extracted_price || Infinity;
    return currentPrice < bestPrice ? current : best;
  }, offers[0]);

  return (
    <div className="space-y-4">
      <h2 className="text-xl font-bold">
        Available from {offers.length} {offers.length === 1 ? 'store' : 'stores'}
      </h2>
      <div className="space-y-3">
        {offers.map((offer, index) => {
          const isBestPrice = offer === bestPriceOffer && offers.length > 1;
          const hasMonthlyPayment = offer.monthly_payment_duration && offer.monthly_payment_duration > 0;

          return (
            <div
              key={index}
              className={`relative flex flex-col gap-4 p-4 rounded-xl border transition-all ${
                isBestPrice
                  ? 'bg-primary/5 border-primary/40 shadow-md'
                  : 'bg-secondary border-border hover:border-primary/30'
              }`}
            >
              {/* Best Price Tag */}
              {(isBestPrice || offer.tag) && (
                <div className="absolute -top-2 -right-2 px-3 py-1 rounded-full bg-primary text-primary-foreground text-xs font-bold shadow-lg flex items-center gap-1">
                  <TagIcon className="w-3 h-3" />
                  {offer.tag || 'Best price'}
                </div>
              )}

              <div className="flex flex-col sm:flex-row gap-4">
                {/* Store Logo & Info */}
                <div className="flex-1 space-y-3">
                  <div className="flex items-center gap-3">
                    {offer.logo && (
                      <div className="relative w-8 h-8 flex-shrink-0">
                        <Image
                          src={offer.logo}
                          alt={offer.merchant}
                          width={32}
                          height={32}
                          className="object-contain"
                          unoptimized
                          onError={(e) => {
                            const target = e.target as HTMLImageElement;
                            target.style.display = 'none';
                          }}
                        />
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <div className="font-semibold text-lg truncate">{offer.merchant}</div>
                      {offer.title && (
                        <div className="text-sm text-muted-foreground line-clamp-1">
                          {offer.title}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Pricing */}
                  <div className="space-y-1">
                    {hasMonthlyPayment ? (
                      <div>
                        <div className="text-3xl font-bold text-primary">
                          {offer.price}
                          <span className="text-sm font-normal text-muted-foreground ml-2">
                            /mo for {offer.monthly_payment_duration} months
                          </span>
                        </div>
                        {offer.down_payment && offer.down_payment !== "$0.00" && (
                          <div className="text-sm text-muted-foreground">
                            Down payment: {offer.down_payment}
                          </div>
                        )}
                        {offer.total && (
                          <div className="text-sm text-muted-foreground">
                            Total: {offer.total}
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="text-3xl font-bold text-primary">{offer.price}</div>
                    )}

                    <div className="flex flex-wrap gap-2 text-sm">
                      {offer.shipping && (
                        <div className={offer.shipping.toLowerCase().includes('free') ? 'text-green-600 dark:text-green-500 font-medium' : 'text-muted-foreground'}>
                          <Package className="w-3.5 h-3.5 inline mr-1" />
                          {offer.shipping}
                        </div>
                      )}
                      {offer.total && !hasMonthlyPayment && (
                        <div className="text-muted-foreground">
                          Total: {offer.total}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Rating & Reviews */}
                  {(offer.rating || offer.reviews) && (
                    <div className="flex items-center gap-3 text-sm">
                      {offer.rating && (
                        <div className="flex items-center gap-1 text-yellow-600 dark:text-yellow-500">
                          <Star className="w-4 h-4 fill-current" />
                          <span className="font-medium">{offer.rating}</span>
                        </div>
                      )}
                      {offer.reviews && (
                        <div className="text-muted-foreground">
                          ({offer.reviews.toLocaleString()} {offer.reviews === 1 ? 'review' : 'reviews'})
                        </div>
                      )}
                    </div>
                  )}

                  {/* Payment Methods */}
                  {offer.payment_methods && (
                    <div className="text-sm text-muted-foreground flex items-center gap-1">
                      <CreditCard className="w-3.5 h-3.5" />
                      {offer.payment_methods}
                    </div>
                  )}

                  {/* Details and Offers */}
                  {offer.details_and_offers && offer.details_and_offers.length > 0 && (
                    <div className="space-y-1">
                      {offer.details_and_offers.map((detail, idx) => (
                        <div key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                          <Check className="w-4 h-4 text-green-600 dark:text-green-500 flex-shrink-0 mt-0.5" />
                          <span>{detail}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Availability */}
                  {offer.availability && (
                    <div className="text-sm text-green-600 dark:text-green-500 font-medium">
                      {offer.availability}
                    </div>
                  )}
                </div>

                {/* View Offer Button */}
                <a
                  href={offer.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-6 py-3 bg-primary text-primary-foreground rounded-full font-semibold hover:opacity-90 transition-opacity flex items-center justify-center gap-2 whitespace-nowrap self-start sm:self-center h-fit"
                >
                  View Offer
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
